# Generated by Django 2.0.4 on 2018-04-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'get_latest_by': ('date', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('name', 'email')},
        ),
    ]
