# Generated by Django 2.0.4 on 2018-04-15 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_task', '0002_auto_20180415_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 4, 15, 19, 59, 49, 728209, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2018, 4, 15, 19, 59, 55, 72112, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_task.Guest'),
        ),
        migrations.AddField(
            model_name='reservationdates',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_task.Reservation'),
        ),
    ]
